name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch, you can change this to any branch you prefer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/unifmu:latest  # Change 'my-image' to the desired image name

    - name: Logout from GitHub Container Registry
      run: docker logout ghcr.io
